language: python
cache: pip
python:
    - 2.7

addons:
    apt:
        packages:
            # build/dev.sh ubuntu-deps
            - python-dev
            - gawk
            - time
            - libreadline-dev
            # test/spec.sh install-shells
            - busybox-static
            - mksh
            - zsh

before_install:
    - test/spec.sh link-busybox-ash

install:
    - pip install flake8 typing mypy_extensions
    # mypy requires Python 3
    - pip3 install mypy
    - build/dev.sh minimal

script:
    # Type checking with MyPy
    - asdl/typed.sh iter-demo
    - asdl/typed.sh iter-arith
    - test/lint.sh travis
    # Unit tests
    - test/unit.sh all
    # Spec tests
    - test/spec.sh smoke
    # TODO: get other spec tests running on Travis.
    # - test/spec.sh all

notifications:
    on_success: change
    on_failure: change  # `always` will be the setting once code changes slow down
